"""Which generator wrote each idea, and (only if you insist) bin the stale unreviewed ones.

Gwilym: "can we stamp each idea with a 'date generated' and which version of the idea generator
generated it? So claude can bulk delete all unreviewed ideas that were generated by an older
version."

  python3 tools/idea_vintage.py                      report: every page, by version and status
  python3 tools/idea_vintage.py --stale g026a4543    what WOULD be removed if you kept only this
  python3 tools/idea_vintage.py --stale g026a4543 --delete --yes-i-mean-it     actually remove it

DELETION RULES, deliberately narrow:
  * only ideas whose status is "new" (never reviewed) are ever eligible. An idea marked Rejected or
    Approved is a human decision and is never touched, whatever wrote it.
  * an idea a person TYPED (genv "manual") is never eligible either, at any age or status. No
    generator wrote it, so no generator version can make it stale.
  * a page is never emptied. If removing the stale ideas would leave a page with none, that page is
    skipped and reported, because an empty creator page is worse than a stale one.
  * every removed idea is written to tools/votes/deleted-ideas-<timestamp>.json BEFORE the write,
    so a mistake is recoverable. The page's own version history is a second net.
  * nothing happens at all without both --delete and --yes-i-mean-it.
"""
import sys, os, json, time, urllib.request, urllib.parse
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PROJECT = "thumbnail-tester-b1746"
BASE = ("https://firestore.googleapis.com/v1/projects/%s/databases/(default)/documents" % PROJECT)
COL = "creator_pages"


def _apikey():
    """The public Firebase web key, read from the frontend source. Not a secret: it identifies the
    project to Firestore and is in the served page already."""
    import re
    src = open(os.path.join(ROOT, "frontend", "build_leads.py")).read()
    m = re.search(r'apiKey:"([^"]+)"', src)
    if not m:
        raise SystemExit("could not find the Firebase web key in frontend/build_leads.py")
    return m.group(1)


def _get(url):
    return json.loads(urllib.request.urlopen(url, timeout=40).read().decode())


def _untype(v):
    """Firestore REST values -> plain Python."""
    if not isinstance(v, dict):
        return v
    for k in ("stringValue", "booleanValue", "doubleValue"):
        if k in v:
            return v[k]
    if "integerValue" in v:
        return int(v["integerValue"])
    if "nullValue" in v:
        return None
    if "arrayValue" in v:
        return [_untype(x) for x in (v["arrayValue"].get("values") or [])]
    if "mapValue" in v:
        return {k: _untype(x) for k, x in (v["mapValue"].get("fields") or {}).items()}
    return None


def _retype(v):
    if v is None:
        return {"nullValue": None}
    if isinstance(v, bool):
        return {"booleanValue": v}
    if isinstance(v, int):
        return {"integerValue": str(v)}
    if isinstance(v, float):
        return {"doubleValue": v}
    if isinstance(v, list):
        return {"arrayValue": {"values": [_retype(x) for x in v]}}
    if isinstance(v, dict):
        return {"mapValue": {"fields": {k: _retype(x) for k, x in v.items()}}}
    return {"stringValue": str(v)}


def pages(key):
    out, tok = [], None
    while True:
        u = BASE + "/" + COL + "?pageSize=300&key=" + key + (("&pageToken=" + tok) if tok else "")
        d = _get(u)
        for doc in d.get("documents") or []:
            out.append((doc["name"].rsplit("/", 1)[1],
                        {k: _untype(v) for k, v in (doc.get("fields") or {}).items()}))
        tok = d.get("nextPageToken")
        if not tok:
            break
    return out


def status(idea):
    st = (idea or {}).get("st") or "new"
    return st if st in ("new", "pre", "ok") else "new"


MANUAL = "manual"


def vintage(idea):
    return (idea or {}).get("genv") or "pre-stamp"


def hand_written(idea):
    """An idea a person typed into the Add-idea box. Never eligible for a bulk cleanup, however
    old and however unreviewed: no generator wrote it, so no generator version can make it stale,
    and losing something a human sat down and wrote is not a tradeoff worth any tidiness."""
    return vintage(idea) == MANUAL


def main():
    args = sys.argv[1:]
    keep = None
    all_unreviewed = "--all-unreviewed" in args
    if "--stale" in args:
        keep = args[args.index("--stale") + 1]
    if all_unreviewed:
        # "let's delete all 'not reviewed' ideas ... That would give us a clean slate while saving
        # anything that's been human-marked." Version-independent: a sentinel no idea can carry
        # makes every never-reviewed idea stale, whatever wrote it.
        keep = "\x00-none-\x00"
    do_delete = "--delete" in args and "--yes-i-mean-it" in args
    if "--delete" in args and not do_delete:
        print("refusing: --delete also needs --yes-i-mean-it\n")

    key = _apikey()
    rows = pages(key)
    print("pages: %d\n" % len(rows))

    by_v, by_status, total = Counter(), Counter(), 0
    for _pid, p in rows:
        for idea in (p.get("ideas") or []):
            total += 1
            by_v[vintage(idea)] += 1
            by_status[status(idea)] += 1
    print("ideas: %d" % total)
    print("  by generator version:")
    for v, n in by_v.most_common():
        print("     %-12s %5d" % (v, n))
    print("  by review status    :")
    for k, lbl in (("new", "never reviewed"), ("pre", "needs Drew"), ("ok", "approved")):
        print("     %-16s %5d" % (lbl, by_status.get(k, 0)))

    if not keep:
        print("\npass --stale <version> to see what an older-version cleanup would remove.")
        print("the version currently live is reported at /  as \"genv\".")
        return

    if all_unreviewed:
        print("\nEVERY never-reviewed idea is eligible, whatever version wrote it.")
        print("Approved and Needs-Drew ideas are kept.\n")
    else:
        print("\nkeeping %s; anything else that is ALSO never-reviewed is eligible\n" % keep)
    plan, skipped, removed_records = [], [], []
    for pid, p in rows:
        ideas = p.get("ideas") or []
        def _stale(i):
            return vintage(i) != keep and status(i) == "new" and not hand_written(i)
        stale = [i for i in ideas if _stale(i)]
        if not stale:
            continue
        left = [i for i in ideas if not _stale(i)]
        if not left:
            skipped.append((pid, len(ideas)))
            continue
        plan.append((pid, p.get("channel") or pid, len(ideas), len(stale), left))
        for i in stale:
            removed_records.append({"page": pid, "idea": i})

    for pid, chan, n, nstale, _left in plan:
        print("  %-26s %3d ideas, %3d would go" % (str(chan)[:26], n, nstale))
    if skipped:
        print("\n  SKIPPED, removal would empty the page:")
        for pid, n in skipped:
            print("     %-26s all %d ideas are stale and unreviewed" % (pid[:26], n))
    print("\ntotal ideas that would be removed: %d across %d pages" % (len(removed_records), len(plan)))

    if not do_delete:
        print("\nthis was a dry run. add --delete --yes-i-mean-it to apply.")
        return

    # OUTSIDE THE REPO. These hold full creator-page contents and the list of who we pitch, and
    # this repo is public: one of these got committed and pushed before anyone noticed.
    bdir = os.path.expanduser("~/Downloads/species-backups")
    os.makedirs(bdir, exist_ok=True)
    backup = os.path.join(bdir, "deleted-ideas-%s.json" % time.strftime("%Y%m%d-%H%M%S"))
    json.dump(removed_records, open(backup, "w"), indent=1)
    print("\nbackup of every removed idea written to %s" % backup)

    ok = 0
    for pid, _chan, _n, _nstale, left in plan:
        url = (BASE + "/" + COL + "/" + urllib.parse.quote(pid)
               + "?key=" + key + "&updateMask.fieldPaths=ideas")
        body = json.dumps({"fields": {"ideas": _retype(left)}}).encode()
        req = urllib.request.Request(url, data=body, method="PATCH",
                                     headers={"Content-Type": "application/json"})
        try:
            urllib.request.urlopen(req, timeout=40).read()
            ok += 1
        except Exception as e:
            print("  FAILED on %s: %s" % (pid, str(e)[:120]))
    print("updated %d of %d pages" % (ok, len(plan)))


if __name__ == "__main__":
    main()
